/// Central SF Symbols registry, the same names synca uses plus the Hearth-specific ones. Views
/// never hard-code a symbol name; add a case here so icons stay consistent.
enum Icon {
    // Shared with synca
    static let sync = "arrow.triangle.2.circlepath"
    static let reload = "arrow.clockwise"
    static let add = "plus"
    static let install = "square.and.arrow.down"
    static let remove = "trash"
    static let folder = "folder"
    static let folderFilled = "folder.fill"
    static let warning = "exclamationmark.triangle.fill"
    static let error = "xmark.octagon.fill"
    static let success = "checkmark.circle.fill"
    static let info = "info.circle.fill"
    static let infoOutline = "info.circle"
    static let activity = "list.bullet.rectangle"
    static let project = "folder.badge.gearshape"
    static let close = "xmark"
    static let copy = "doc.on.doc"
    static let reveal = "arrow.up.forward.app"
    static let play = "play.fill"
    static let sparkles = "square.grid.2x2"
    static let check = "checkmark"
    // Hearth
    static let flame = "flame"
    static let flameFilled = "flame.fill"
    static let addFolder = "folder.badge.plus"
    static let shared = "externaldrive.connected.to.line.below"
    static let recipe = "cube"
    static let service = "square.stack.3d.up"
    static let stop = "stop.fill"
    static let restart = "arrow.clockwise"
    static let trust = "checkmark.shield"
    static let log = "terminal"
    static let earlier = "clock.arrow.circlepath"
    static let latest = "arrow.down.to.line"
    static let link = "arrow.up.right.square"
    static let reclaim = "bolt.trianglebadge.exclamationmark"
    static let workspaceMissing = "exclamationmark.triangle"
}
